In [19]:
import pandas as pd

file_path = 'statistics.xlsx'
sheet_name = 'week_province'

df = pd.read_excel(file_path, sheet_name, engine= 'openpyxl')
df.head()

,Beijing,Tianjing,Shanghai,Chongqing,Hebei,Shanxi,Liaoning,Jilin,Heilongjiang,Jiangsu,...,Gansu,Qinghai,Taiwan,Inner Mongolia,Guangxi,Tibet,Ningxia,Xinjiang,Hongkong,Macau
0,4,1,3,3,2,3,1,0,1,2,...,2,1,3,1,2,2,0,3,1,1
1,4,2,4,1,4,3,1,1,5,3,...,1,0,2,4,2,1,0,2,0,1
2,5,1,2,2,3,2,1,1,3,3,...,1,0,1,1,3,0,0,0,2,2
3,4,1,3,2,5,3,3,0,4,4,...,5,3,7,1,2,1,1,0,3,4
4,7,3,5,4,3,4,4,3,3,4,...,3,1,6,0,3,1,1,3,0,0

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams['font.sans-serif']=['SimHei']   # 用黑体显示中文
matplotlib.rcParams['axes.unicode_minus']=False     # 正常显示负号

import bar_chart_race as bcr
bcr.bar_chart_race(
    df=df.reset_index(drop=True),
    filename='xwlb.mp4',
    orientation='h',
    sort='desc',
    n_bars=6,
    fixed_order=False,
    fixed_max=True,
    steps_per_period=10,
    interpolate_period=True,
    label_bars=True,
    bar_size=.95,
    period_label={'x': .99, 'y': .25, 'ha': 'right', 'va': 'center'},
    period_fmt='Week - {x:.2f}',
    perpendicular_bar_func='median',
    period_length=1000,
    figsize=(5, 3),
    dpi=600,
    cmap='dark12',
    title='Provinces Mentioned Times in XWLB by week',
    title_size='',
    bar_label_size=7,
    tick_label_size=7,
    shared_fontdict={'family' : 'SimHei', 'color' : '.1'},
    scale='linear',
    writer=None,
    fig=None,
    bar_kwargs={'alpha': .7},
    filter_column_colors=True)

D:\anaconda3\envs\nlp\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
D:\anaconda3\envs\nlp\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))